<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260301103643 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, theme VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095A61220EA6 ON activity (creator_id)');
        $this->addSql('CREATE TABLE activity_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, user_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_22921A78A76ED395 ON activity_member (user_id)');
        $this->addSql('CREATE INDEX IDX_22921A7881C06096 ON activity_member (activity_id)');
        $this->addSql('CREATE TABLE bill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_amount DOUBLE PRECISION NOT NULL, drink_type VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7A2119E381C06096 ON bill (activity_id)');
        $this->addSql('CREATE TABLE bill_share (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vote_score INT NOT NULL, rank INT NOT NULL, percentage DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, bill_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D9F6C8C41A8C12F5 ON bill_share (bill_id)');
        $this->addSql('CREATE INDEX IDX_D9F6C8C4A76ED395 ON bill_share (user_id)');
        $this->addSql('CREATE TABLE rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, points INT NOT NULL, is_default BOOLEAN NOT NULL, activity_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_46D8ACCC81C06096 ON rule (activity_id)');
        $this->addSql('CREATE TABLE vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, voter_id INT NOT NULL, target_id INT NOT NULL, activity_id INT NOT NULL, rule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A108564EBB4B8AD ON vote (voter_id)');
        $this->addSql('CREATE INDEX IDX_5A108564158E0B66 ON vote (target_id)');
        $this->addSql('CREATE INDEX IDX_5A10856481C06096 ON vote (activity_id)');
        $this->addSql('CREATE INDEX IDX_5A108564744E0351 ON vote (rule_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A61220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_member ADD CONSTRAINT FK_22921A78A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_member ADD CONSTRAINT FK_22921A7881C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bill ADD CONSTRAINT FK_7A2119E381C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bill_share ADD CONSTRAINT FK_D9F6C8C41A8C12F5 FOREIGN KEY (bill_id) REFERENCES bill (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bill_share ADD CONSTRAINT FK_D9F6C8C4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rule ADD CONSTRAINT FK_46D8ACCC81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564EBB4B8AD FOREIGN KEY (voter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564158E0B66 FOREIGN KEY (target_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A10856481C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564744E0351 FOREIGN KEY (rule_id) REFERENCES rule (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A61220EA6');
        $this->addSql('ALTER TABLE activity_member DROP CONSTRAINT FK_22921A78A76ED395');
        $this->addSql('ALTER TABLE activity_member DROP CONSTRAINT FK_22921A7881C06096');
        $this->addSql('ALTER TABLE bill DROP CONSTRAINT FK_7A2119E381C06096');
        $this->addSql('ALTER TABLE bill_share DROP CONSTRAINT FK_D9F6C8C41A8C12F5');
        $this->addSql('ALTER TABLE bill_share DROP CONSTRAINT FK_D9F6C8C4A76ED395');
        $this->addSql('ALTER TABLE rule DROP CONSTRAINT FK_46D8ACCC81C06096');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564EBB4B8AD');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564158E0B66');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A10856481C06096');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564744E0351');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_member');
        $this->addSql('DROP TABLE bill');
        $this->addSql('DROP TABLE bill_share');
        $this->addSql('DROP TABLE rule');
        $this->addSql('DROP TABLE vote');
    }
}
